### PR TITLE
Changing the main character and adding some ASCII art

### PR DESCRIPTION
**Pull request by floridop**
Changed some content of your story. You are free to ask me to do any change you like before approving!

### CODE REVIEW

**Review by sherwan24 — APPROVED** [review]
I think that the **terrifying** _princess_ is beautiful. We should keep it!

**Comment by floridop** [comment]
Ok, do you want me to do more things before the merge? (you should read slides 76-82 to know what to do, you're the release manager in this scenario)

**Comment by floridop** [comment]
Hi @sherwan24 

The objective of the exercise is that you, as the release manager, will integrate my changes in your repository. In order to do this, you must *merge* my pull request request if you think it's ok.

Approving the changes just tells me that you're happy with my changes, but doesn't integrate them. if you want to integrate them in your repository you need to merge as explained in slide 80. If you want me to do other changes you can ask.

You claim you did the actions in slides 72-82 but I think you completely missed slides 79-82. Please read them carefully thinking that you're the release manager.

**Comment by floridop** [comment]
I'll close this part of the homework, but if there is something else 
you're curious to try and I am available I'll be happy to test.

**Pull request merged**
